### ISSUE TITLE
Combine device and template files

### ISSUE THREAD

**Issue by XargonWan** [RetroMan-project/core#1]
Read the device file, find its template by checking if the file  `templates/<id>.yaml` is present and virtually merge them in a dictionary.

Example, RetroMan is calling the device named `My Miyoo Mini` so ti looks for a folder named `My Miyoo Mini` in the `devices` folder.
The folder is found so the file "My Miyoo Mini.yml" is searched.

The file is found, it contains:
"My Miyoo Mini.yml"
```yml
id: miyoominiv3-onion
friendly_name: Miyoo Mini (OnionOS)
device_root: /home/public-folder/gits/RetroMan/test/My MIyoo Mini
force_decompression: true
```

This device is calling for the id `miyoominiv3-onion`, so RetroMan searches for a `miyoominiv3-onion.yml`, and finds:
```
# Miyoo Mini v3 - OnionOS
miyoominiv3-onion:
  name: Miyoo Mini
  template_version: 0.1
  brand: Ingenic
  gamelist_file: miyoogamelist.xml
  saves: Saves/CurrentProfile/saves
  states: Saves/CurrentProfile/states
  roms_path: ROMs
  systems:
    - gb:
        - status: "supported" # This is the default status, can be omitted
        - emulators:
          - gambatte:
              default: true
              saves: _savesdir_/Gambatte
              states: _statesdir_/Gambatte
    - gbc
    - nes
    - snes
    - megadrive
    - dreamcast:
        - status: "available"
```

This is put into a dictionary.

At this point it scans for all the systems and searches for their missing information inside the `library.yml`, and it finds for example of megadrive:

```
    - megadrive:
        name: Megadrive
        manifacturer: Sega
        name_us: Genesis
        release_jp: 29-10-1988
        release_eu: 01-11-1990
        release_us: 14-07-1989
        release_uk: 14-08-1990
        release_br: 01-12-1990
        system_folders:
          - megadrive
          - genesis
        extensions:
          - 68k
          - mdx
          - md
          - sgd
          - smd
          - gen
          - bin
          - zip
          - 7z
```

In this case the dictionary is updated as the following:

```
# Miyoo Mini v3 - OnionOS
miyoominiv3-onion:
  name: Miyoo Mini
  template_version: 0.1
  brand: Ingenic
  gamelist_file: miyoogamelist.xml
  saves: Saves/CurrentProfile/saves
  states: Saves/CurrentProfile/states
  roms_path: ROMs
  systems:
    - gb:
        - status: "supported" # This is the default status, can be omitted
        - emulators:
          - gambatte:
              default: true
              saves: _savesdir_/Gambatte
              states: _statesdir_/Gambatte
    - gbc
    - nes
    - snes
    - megadrive:
        name: Megadrive
        manifacturer: Sega
        name_us: Genesis
        release_jp: 29-10-1988
        release_eu: 01-11-1990
        release_us: 14-07-1989
        release_uk: 14-08-1990
        release_br: 01-12-1990
        system_folders:
          - megadrive
          - genesis
        extensions:
          - 68k
          - mdx
          - md
          - sgd
          - smd
          - gen
          - bin
          - zip
          - 7z
    - dreamcast:
        - status: "available"
```

And so on for all the other systems.

**NOTE:** in case of conflicts the `library.yml` is weaker than the template file `miyoominiv3-onion.yml` that wins over the library.

**NOTE2:** the entry emulator and folder are mandatory in every device template and they're not inherited by library.
Otherwise when a game is copied onto the device, the engine will not know in which folder to put it.
